### PR TITLE
Update api spec

### PR DESCRIPTION
**Pull request by jessfraz**
Updating the spec from that in the api repo

### CODE REVIEW

**Comment by paultag** [comment]
I'm not particularly good with TypeScript; would something like this fix the gen failure:

```diff
diff --git a/src/modelsGen.ts b/src/modelsGen.ts
index a071b11..4c55ddf 100644
--- a/src/modelsGen.ts
+++ b/src/modelsGen.ts
@@ -95,6 +95,8 @@ async function main() {
           }
           if (subSchema.type === 'object' && (subSchema as any).properties) {
             return `${key}: ${makeTypeStringForNode(subSchema, key)}`;
+          } else if (subSchema.type === 'object') {
+            return `${key}: object`;
           }
           console.log(subSchema, key);
           throw 'subSchema not implemented ' + subSchema.type;
```

The idea here is that if there's an empty struct type, it has no `properties` (as seen above), and treating it as a raw `object` is fine, since we don't have any specific properties beyond treating it as an empty `{}`. I don't know if this code is called with any other instances where we'd have an object but want to fail rather than generate an `{}`. @jessfraz

**Comment by Irev-Dev** [comment]
That works @paultag, I would also be okay with 
```
return `${key}: any`;
```
But I guess object is slightly better than any.

Just want to clarify that this isn't a problem with the OpenAPI spec? Why is there an object with no specified properties? that's because we want it to be flexible?

If we wanted to support this specific case, but in future still want it to fail when the spec doesn't have more specific types we could do something like
```typescript
          if (
            subSchema.type === 'object' &&
            (schema?.properties?.type as OpenAPIV3.SchemaObject)?.enum?.[0] ===
              'metrics_request'
          ) {
            // comment giving context
            return `${key}: object`;
          }
```

**Comment by paultag** [comment]
@Irev-Dev this'll also happen for the `Ping` type -- they both have no arguments (well, at least currently). The message type itself is significant, it just has no properties that will be set/accessed

**Comment by Irev-Dev** [comment]
Okay, just make your best judgement and commit it I think 👍 

I think maybe we're crossing wires about ping though, I can't see anything `type: object` in the spec for ping, and further adding the change you suggested gives this diff to [models.ts](https://github.com/KittyCAD/kittycad.ts/commit/ebce503b9f582444435b1c58106dbe1422264c90), one small change around ping, but nothing to do with an untyped object.

**Comment by paultag** [comment]
I sent this up as PR https://github.com/KittyCAD/kittycad.ts/pull/176, figure that'll let the checkboxes go green in order

**Pull request merged**
